export const CREATE_CARD_INWORK = 'CREATE_CARD_INWORK'; 
export const CREATE_CARD_ONCHECK = 'CREATE_CARD_ONCHECK'; 
export const CREATE_CARD_DONE = 'CREATE_CARD_DONE'; 
export const ADD_ID_CARD = 'ADD_ID_CARD';
export const NAME_CARD = 'NAME_CARD;';
export const EDITOR_CARD_INWORK = 'EDITOR_CARD_INWORK';
export const EDITOR_CARD_ONCHECK = 'EDITOR_CARD_ONCHECK';
export const EDITOR_CARD_DONE ='EDITOR_CARD_DONE;' 
